CLASS ycx_mb12_path_fail DEFINITION
  PUBLIC
  INHERITING FROM cx_no_check
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ycx_mb12_path_fail IMPLEMENTATION.
ENDCLASS.
