CLASS ycx_mb112_wrong_params DEFINITION
  PUBLIC
  INHERITING FROM cx_no_check
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ycx_mb112_wrong_params IMPLEMENTATION.
ENDCLASS.
