CLASS ycl_mb11_nav_go2_most_gifts DEFINITION
  PUBLIC
  INHERITING FROM ycl_mb11_navigator_random
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ycl_mb11_nav_go2_most_gifts IMPLEMENTATION.
ENDCLASS.
